### ISSUE TITLE
umap test fails

### ISSUE THREAD

**Issue by wspear** [E4S-Project/testsuite#73]
@egreen77 Recent versions of umap have the umap test failing with the text Test failed. and no other information.

**Comment by egreen77** [comment]
Hi,

Unfortunately, the umap test is very dependent on the system environment it's run in. The test environment needs to meet the requirements listed here: https://github.com/LLNL/umap/blob/develop/README.md#runtime-requirements

The test code performs a basic functionality test and returns a failure status if it determines umap won't be usable in the current environment due to missing functionality or restricted permissions. I'm not really sure if there's a better way to handle this.

**Comment by wspear** [comment]
I'll check that value in the run script for the test so we can get informed of the reason for the failure.
